image: gitpod/workspace-dotnet
tasks:
  - init: dotnet restore
    command: dotnet restore && dotnet watch --project . run --urls "http://0.0.0.0:5000;http://0.0.0.0:5001"
    name: Debug-watch
  - command: |
      curl -o kafka.tgz https://downloads.apache.org/kafka/2.8.0/kafka_2.12-2.8.0.tgz \
      && tar -xvf kafka.tgz \
      && rm kafka.tgz \
      && mv kafka_* k \
      && cd k \
      && bin/zookeeper-server-start.sh -daemon config/zookeeper.properties \
      && bin/kafka-server-start.sh config/server.properties &
    name: KafkaServer
  - command: |
      sleep 15
      k/bin/kafka-console-consumer.sh --topic monTopic --from-beginning --bootstrap-server localhost:9092 &
    name: KafkaConsumer
  - command: |
      sleep 20
      J2K_URL=$(gp url 5001)
      curl -d '{"key1":"value1", "key2":"value2"}' -u admin:admin -H "Content-Type: application/json" -X POST $J2K_URL/api/msg
    name: J2KConsole
vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
ports:
  - port: 2000-10999
    onOpen: ignore
  - port: 5001
    onOpen: open-preview
