branches:
  except:
  - "/^untagged/"
language: csharp
mono: none
dotnet: 3.1
script:
- dotnet restore && dotnet publish -c release -o app --runtime linux-x64 --self-contained
  false /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=false
deploy:
  provider: releases
  api_key:
    secure: SKfm3Yd/ASVnkm7/ufylBBNI6W9c08Wub8BzOyGxvOWbojjnge4sMWF5Jh0ekW6GAtjmgYWZFxHIIAssRDRbTbiw9C1P8UL1+voHBU5cAwrKM9NpIsCHDILRlYtZz5Lb2LN5lfs83fuZnx35MKrqwaiy0M9LjRRRf2hPTfJsV5EnO+Lj0vtQ5qHy0T6bH3aMzU/r/d+SB7MDJa3i1JmpijMFz4F/LUIKo6O16AAc7oEfd9fxtOaMdlJQWYKwyUvFqFz3zug3xYDIsOUucFuxtFvlDsy7qV+UemMBZm3iT2UYkVVTyEjL6E5u7gMEiijmlniCngE90qTAemqfikC+6nbKGtmd6QcoaLpyKiuBb8DfWyt53iI4lZMm33FVxlUwCT4KEvmd05hrmMy06eNBN3NLL9EUBCxBO0NohVhQ6+AR4bs5a4wjKzF9OMjHGjUZoLhZc/ZA2B3A3qP2X+lvKfH8poTSzl0nO0qMadrzWtuT/WK5N1cIjkNuaUJMhWOHITSJUrP2YP/kKlf66612v3grHKjNISag9F3FGk2qhwl7ET/NPmWF3/FngtHNKk2zADbLy1glIpcMpRxcNHoEnwdADalxITOSm2ntm9sGp6TDw6Z+Sm+pk7aowxl0KYF7fJff+pG9JWPYSJwmZ8ApjlhJ8dHKxAjiWmOWJ7C37o8=
  file: app/*
  on:
    repo: lefebsy/json2kafka
  skip_cleanup: 'true'
env:
  global:
  - secure: F51uguqCVVC1Pg9/t4Of2+GfYwKtahaRaKQx/dsrXFZLsbSlBllnY6dIF5HccgND79npxOYoTAvtkbLZA1/HP1ljJFVZhf8VQXlJeb7JUeFQnHIsW4AGLDme0wmfHF2ucOcVsldBsDCrELlum5M2qRvL6vtWkSWyiPcLbrU4nQz17tl240SWQwXUjBFFgkISxj6EI/ZOVLlaf5nLoiTPmDFhPpUok2TjAmyOYGAy+3HbohPgRBWgUoQyas8A6Dx4Jx1xJVthcgjsYUNqvyf7h7EPtdD8hs6/po9i8J+CfIbjCFK0WRNzfq2cyr1KQrCCbXQmoiKXIRRgHJuQHq2kZqsF1YirsHTHS9D+dkZllb6j3+3Rn1DpFVXEVswM5VAQ3Re3gC+tpFs0gi2aMxbOcPSwR84pQ6B9bN+7+MAC4cBwgcyOntz7mI3u2ffjNnwftq5JKRsKetmnNgzJ5J6nQJfxriEsAVONeEAib4Nm+oGbWvZfjPQTQLs7nJtLLLrb/jwcgmrr3xCiB9951mffkloqMxyo0R0TTJzM7m2I4DCKbC1Ahmy6SZtrlFWs3iWbqQmhgECh6/y2kbyi0OjcB2eKKNJ8QBavCIg9OjsU+k87N521uIme09EbwLx8mLxcY9kLZeQix8xIc4g25VCk+C1AObUCifjLhMcxeg92/Bo=
