branches:
  except:
  - "/^untagged/"
language: csharp
mono: none
dotnet: 3.1
script:
- dotnet restore && dotnet publish -c release -o app --runtime linux-x64 --self-contained
  false /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=false
deploy:
  provider: releases
  api_key:
    secure: yBTpXro3D1zjn3x09190icSt9ViOPwOauxVCySlOjsUJuRVYvejYsZD1jpFbAYvcIj+9/p6AfUfQCDG5N44bdt0KBV1uIRuFgZtLBv8/mYCvqXKpBITLqkyH8Wq+jv6TjgfOyiFTMGnlQBvbZbNUFIMI6CsBm/NDne7bPpob1PfQJllVvbP7mogFgeoq/cPidkjCfY0SxxqLrVyW/l6GOSpm/3BhToF5O6zYBOGmapg6/d7DFUebc0BTu0ucUqhW4HCFipyVUuYGNMTFuRbXJwEVxAxh3yKht7SustmeKV39Fgq5JcVVkPvIEG5zuvJ144q6a0DRjl759Q9nEJKb2NR5EMrzvTUms02yLIdnN+GhOqzz/QH3fix9jWmnzlWU+3mP7oLxyCGRhUt/81QCiDEb6pJ5OOenOs39R+lm9M9tZJKMWPThVfip5nhQL0l3MvWbUD+yN5ZtPRS7tdnzbvbHD8y17ntOSkjTvM5BGAImj9iJMd6bfyE/SysyvjLCtYF/yXRIZKYRL/4LBa+fHiwtvwDDm7JzsHkcF/vsR3uU44N0vjQgD6vHQ1y95toQ4bR/1kg6z03gJdtruAr1sFWCswjPgTL9sn+uB9ng00703VQ6rCpPYij5x71Q8NN1uo84OujV389E4YWE1jinVm53WDa5l9D9jgpwnlf+yKw=
  file: app/*
  on:
    repo: lefebsy/json2kafka
    tags: true
  skip_cleanup: 'true'
