branches:
  except:
  - "/^untagged/"
language: csharp
mono: none
dotnet: 3.1
script:
- dotnet restore && dotnet publish -c release -o app --runtime linux-x64 --self-contained
  false /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=false && zip -r linux.zip app
deploy:
  provider: releases
  api_key:
    secure: kGBRAoXvfzmzUd8w+/NOUMKlQ0yKhx1fZNggT9XSgtKIvTQNtAfDFh7pf1CtslNycnf7/MZ95SDlAcftokDrDQKHbQoNHqLoqUtTg+mZeauqIBKR+jqxKqSx4YhG7josplGYqOuSPtYlZNo2SpYxVVEoyihziUL8BCt7ENFvOKLmsoJSX3TVre1xYc5ARVsUcCKVfwuq7JdNmOcRXV1YuIcQjAfNEAvAHkdM3lnPr/+ZL06amtcLbg3/yboe4uw/nqhcNQMvzwGOh/sIWo0xjL011TSg78CpbEWAfuEUlrKwGIYYtzEHEkEcPldn8wnQnnTWi1u8nXJk1O+Egfv+VzP0NMp2UNxvXPkxGD/8s4TxY92bO/RiZUWC6Sq9h1XPC9qgDGLA2wdIRi4umyIexTu0Z/wHE607Hhe66TE++HODkDp0hhHGl1ltIuPJ6jGKsUNzsDhPqxQ6Zo4lYPx4LenDZuFZXrBPNg5NEH8F5Hboh/DqvMLEMiCB4QM0jQPAx3d2Yt0AXYgxjt3gNmTI8LnTz/EmgOtt/v23+V5RmIVNoTKdBo9kuYDDI6qdJlnxNW9vXyymjLVxk+GEfO6WQKX0O2OuTbo3fjGdHPoUWbjdYfNUItyonxwaccga1dLAU5AKh50UcaA+XGBhQL7LL0MJ1s5/GYJ/cpIb6jelMOg=
  file: linux.zip
  on:
    repo: lefebsy/json2kafka
    tags: true
  skip_cleanup: true
  file_glob: true
env:
  global:
  - secure: F51uguqCVVC1Pg9/t4Of2+GfYwKtahaRaKQx/dsrXFZLsbSlBllnY6dIF5HccgND79npxOYoTAvtkbLZA1/HP1ljJFVZhf8VQXlJeb7JUeFQnHIsW4AGLDme0wmfHF2ucOcVsldBsDCrELlum5M2qRvL6vtWkSWyiPcLbrU4nQz17tl240SWQwXUjBFFgkISxj6EI/ZOVLlaf5nLoiTPmDFhPpUok2TjAmyOYGAy+3HbohPgRBWgUoQyas8A6Dx4Jx1xJVthcgjsYUNqvyf7h7EPtdD8hs6/po9i8J+CfIbjCFK0WRNzfq2cyr1KQrCCbXQmoiKXIRRgHJuQHq2kZqsF1YirsHTHS9D+dkZllb6j3+3Rn1DpFVXEVswM5VAQ3Re3gC+tpFs0gi2aMxbOcPSwR84pQ6B9bN+7+MAC4cBwgcyOntz7mI3u2ffjNnwftq5JKRsKetmnNgzJ5J6nQJfxriEsAVONeEAib4Nm+oGbWvZfjPQTQLs7nJtLLLrb/jwcgmrr3xCiB9951mffkloqMxyo0R0TTJzM7m2I4DCKbC1Ahmy6SZtrlFWs3iWbqQmhgECh6/y2kbyi0OjcB2eKKNJ8QBavCIg9OjsU+k87N521uIme09EbwLx8mLxcY9kLZeQix8xIc4g25VCk+C1AObUCifjLhMcxeg92/Bo=
