branches:
  except:
  - "/^untagged/"
language: csharp
mono: none
dotnet: 5.0
script:
- dotnet restore && dotnet publish -c release -o app --runtime linux-x64 --self-contained
  false /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=false && zip -r
  linux.zip app
deploy:
  provider: releases
  api_key:
    secure: inZkM6NUw+Gj4OJWfnXH3N6KIfyjx8rmSFJfu8XzeWPolFzgZupv2kY5EcSGMY1MOTnRFAMmbWdNpE0fU2NyVVew2gxUWya4NJqtBzphcy0TS0slnm3gkR9Cilve4AyIUBhvYmyMB9B2zQlSnwVLBh7mbdJZENZmGUwu2a0kACH5Aqtmc0AE1GWnU5UP10nmbeyTV4VKKL8+V01SJi2jC5Rv6BDTqlzBWeiragO/WrrCa1ZXvorUkUFHPdvmNaYvy4HQjYdLlYVXXXg6QlEvZLP5jV+xD01veINeq2SzXzQiJrS/5sRI13Yb5pYRwg9WvQ8Sdh4R04VmgcMdOV2dwqYQ5CsWvZ/eLH3DUCXmCkNsh243oMo++JDl/hTsCIHFbs7txin8VHRxENaoz5fXN2yZdV/AZJ4Ra0Cw/oMOYvh1J98YyYGHBPen4VfiQG+VCCfhFTI8fEBHxNq7q2LuywnjYWjk3BfXv1x98Qz2Fbjlf4oBz81EWyQX0gQ2vMqL+4cmLPjIZADdVU0Go6hhpUuRWFzTZ+iDBP7oL5483sD8gL4Td9CMllSm0DKfTVwafcLBQPy79T7+X3+hli9OMReKnyrlBB/dheNl05V8PnDPkSKeOMtwM4qgby4/AH0WfiiKnl6CuNNU9EWyCzB2kSvUXbfBTHnQZu8MJeN31Xk=
  file: linux.zip
  on:
    repo: lefebsy/json2kafka
    tags: true
  skip_cleanup: 'true'
