branches:
  except:
  - "/^untagged/"
language: csharp
mono: none
dotnet: 3.1
script:
- dotnet restore && dotnet publish -c release -o app --runtime linux-x64 --self-contained
  false /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=false
deploy:
  provider: releases
  api_key:
    secure: "eobDub9r1E5dQF4vcAmEclkttYFgdPKpSq1tkE6vDUp6FMVGejHdp5hj650rwhr2zN+qZA+gVEyoSxlGOrgnIdQor9kmWc/yn8w6fp95TgjxrDFBRu4g9m6gRwtJVKZV+NZxojO9lURwSX/ZsW+RcH8CbHDfy8sSxSpCRxRFV9Y7pVXTEDB48u4zez7nGxSkwlhbeNabpewHO9DqstJXcfnWSiaiws1D4Zcq317mRvMyl45aOYEQOgpT9/JhgVhBnTAKx3WnlVYy+9mLZrxOWZyK1kF6hzbXJcFgGkEPCG/6XSIX4W2iQAGRmlqUin+jgpmuPq3Jxk4sYd+ddRFeKTNzux5kxLmJLGxeEo+dFdAUMuaeyyU2y4Aderq1rNtVs5N9fGGJXVKS8iFNhVbsvuSvkZZ89ngnzQV6PgbTm0QjeGuDIUC3LSkFNaM/V9gxIeZIaYd330UXXGBhwM95INf0HLLQr5fvVoW85qGDnt/QSF1nF1UU34edRAsHt64w9nu5yEfrEJWObQU/ZvQi/xE6GZzpKl2Bb+Ad+bQYRqQfnF/ycgcsTCqLtTWFDw1lTTWHCPGfQMNhHfKe8TeqKBRsWgqoxwDSh0RMG27pEHjTv34ehaMTBinhjy53LsK7WIweRfqXGGjRVZvUmcXQ3C8NjqcJvlmA84VnDp3EkDw="
  file: app/*
  on:
    repo: lefebsy/json2kafka
    tags: true
  skip_cleanup: 'true'