branches:
  except:
  - /^untagged/
language: csharp
mono: none
dotnet: 3.1
script:
- dotnet restore
deploy:
  provider: releases
  api_key:
    secure: Qs0rQTSl0EGhel9q5iQx6jPNxGmIhueYVR/nMeLcGs/ZHu0vS8r2/cfMDGIolSARTHiRIb94Ysr0gln5FkGiFgXp3Lo9oYZ7/K5t+6EjlNM4lGkg1eRppulxtv1SpcSCcSPlXbXEjnpXsJtajNpzbuu+QzjVEY/r5USzZDuQS8JnNaQh4vw+9QxuTtGUboX8m1rKAnVxAQX5vWM/xmusgQ/wM1Qs0+kJolNWM0d7YrMCI69ZaxR0DkDsFs/XHCRFrApEIAo3zYdW4N42Hdu2IH6rVomfCgvfmXhOKSGKY4IQ7DwHWlxGr8y4HMsM/Te78aOgsxjZlYNPw7JksQUcdxb1fFeVq5Gyqms2BhQxDkopqhHuiApnjtqOkxJkof0cT1meqc+87TvXNv4czaEI/0k7EzQbgGQ9mLLhOplbI6XoG7kMYIphombBI41FsQyFKg8ip+E23kyor6JcWoWJcO/GXI9u8d1cKF5A/2iueZnSYIY3J3Bd8xMt1318qR2LublyO61E1ebPw+STMU4TK+Vtw/DpUiOqApckwsW//SDHpOSYhn1IQ8CqsIjrgbL0LwfXZie7r0T+sND2JF4M8r4f6jTUy7P1M7isxOysGNytJrX/SjyamvHcqvKeUNII3FRYUQ7KRQPMxD84UXaG3Q4xTgs5knexO4gq1RsPO/k=
  file: app/*
  on:
    repo: lefebsy/json2kafka
  skip_cleanup: 'true'
